import type { JsonValue } from "@bufbuild/protobuf";

/** Invalid metadata, not merely stale digests: the test independently resigns
 * each case using generated ProtoJSON before asking the consumer to reject it.
 */
export const invalidMetadata: readonly (readonly [string, JsonValue | undefined])[] = [
  ["/workspaceId", ""], ["/namespaceId", "../other"],
  ["/proxyId", "0191b7f1-7f2c-4c13-9a61-2f29f2be1001"], ["/revisionId", ""],
  ["/configHash", "not-a-hash"], ["/generation", "0"],
  ["/resourceUrl", "http://proxy.apex.test/mcp"], ["/auth/audience", "https://other.apex.test/mcp"],
  ["/spec/ingress/host", "different.apex.test"], ["/spec/ingress/path", "/other"],
  ["/spec/ingress/protocolRevision", "2099-01-01"],
  ["/spec/ingress/inboundAuthenticationRequired", false],
  ["/spec/ingress/transport", "MCP_PROXY_TRANSPORT_STDIO"],
  ["/spec/ingress/allowedOrigins", ["http://console.apex.test"]],
  ["/spec/upstreams/0/transport", "MCP_PROXY_TRANSPORT_STDIO"],
  ["/spec/upstreams/0/endpointOrCommandRef", "https://user:SENSITIVE@portfolio-api.apex.test/mcp"],
  ["/spec/upstreams/0/credentialRef", "SENSITIVE"], ["/spec/upstreams/0/credentialRef", "secret://"],
  ["/spec/upstreams/0/serverIdentity", ""], ["/spec/upstreams/0/toolCatalogHash", ""],
  ["/spec/exposedTools", []], ["/spec/exposedTools/0/upstreamId", "unbound"],
  ["/spec/exposedTools/0/alias", ""],
  ["/spec/cliProfiles", [{ profileId: "unsupported", shell: true }]],
  ["/spec/governanceBinding/policyId", ""],
  ["/spec/governanceBinding/approvalMode", "operator"],
  ["/spec/governanceBinding/dataClassification", "unknown"],
  ["/spec/governanceBinding/rateLimit", "0/m"], ["/spec/governanceBinding/concurrencyLimit", "0"],
  ["/spec/governanceBinding/budget", "unlimited"], ["/spec/governanceBinding/retention", "3651d"],
  ["/spec/runtimeProfile/rootless", false], ["/spec/runtimeProfile/networkPolicy", "allow-all"],
  ["/spec/runtimeProfile/filesystemPolicy", "read-write"],
  ["/spec/runtimeProfile/cpuLimit", "0.5m"], ["/spec/runtimeProfile/cpuLimit", "18446744073709551616"],
  ["/spec/runtimeProfile/memoryLimit", "256Mystery"], ["/spec/runtimeProfile/memoryLimit", "18446744073709551615Gi"],
  ["/cpuMillis", 501], ["/cpuMillis", 0], ["/cpuMillis", 4001],
  ["/memoryBytes", "268435457"], ["/memoryBytes", "0"], ["/memoryBytes", "2147483649"],
  ["/pidLimit", 0], ["/pidLimit", 1025],
  ["/imageRef", "registry.example.test/apex/mcp-gateway:latest"],
  ["/imageRef", "sha256:" + "a".repeat(64)],
  ["/imageRef", "registry.example.test/apex/mcp-gateway@sha256:" + "f".repeat(64)],
  ["/secretRefs", []], ["/secretRefs", ["SENSITIVE"]],
  ["/toolSchemas", []], ["/toolSchemas/0/toolName", "unexposed"],
  ["/toolSchemas/0/inputSchemaJson", ""], ["/toolSchemas/0/outputSchemaJson", ""],
  ["/toolSchemas/0/outputSchemaJson", '{"type":"object","$ref":"https://SENSITIVE.test/schema"}'],
  ["/toolSchemas/0/inputSchemaJson", '{"type":"object","type":"object"}'],
  ["/toolSchemas/0/outputSchemaJson", '{"type":"array"}'],
  ["/toolSchemas/0/outputProfileId", ""], ["/toolSchemas/0/schemaHash", ""],
  ["/networkGrants", []], ["/networkGrants/0/grantId", ""],
  ["/networkGrants/0/port", 8443], ["/networkGrants/0/privateDestination", true],
  ["/networkGrants/0/approvedCidrs", ["not-a-cidr"]],
  ["/networkGrants/0/approvedCidrs", ["0.0.0.0/0"]],
  ["/networkGrants/0/approvedCidrs", ["127.0.0.1/32"]],
  ["/networkGrants/0/approvedCidrs", ["169.254.169.254/32"]],
  ["/auth/issuer", ""], ["/auth/jwksUri", "http://issuer.example.test/jwks"],
  ["/auth/requiredScopes", []], ["/auth/workloadIdentityRef", "SENSITIVE"],
  ["/telemetry", undefined], ["/telemetry/fullTraceSamplePerMillion", 1000001],
  ["/telemetry/maxStages", 33], ["/telemetry/maxSummaryBytes", 65537],
  ["/telemetry/maxSpans", 129], ["/telemetry/maxAttributesPerSpan", 65],
  ["/telemetry/maxExportQueueBytes", "18446744073709551615"],
];
