"""Create host-restricted copies of the Docker-readable test secrets."""

from __future__ import annotations

from pathlib import Path


def _prepare_write(path: Path) -> None:
    if path.is_symlink():
        raise RuntimeError(f"refusing to overwrite symbolic link: {path}")
    if path.exists() and not path.is_file():
        raise RuntimeError(f"refusing to overwrite non-file path: {path}")
    if path.exists():
        try:
            path.chmod(0o600)
        except OSError:
            pass


def _is_private_secret_name(name: str) -> bool:
    lower = name.lower()
    return (
        lower.endswith(".key")
        or lower.endswith("-password")
        or lower.endswith("_password")
        or lower in {
            "nats-username",
            "nats-password",
            "control-nats-username",
            "control-nats-password",
            "valkey-ingest-password",
            "valkey-control-password",
            "ingest-bearer-token",
        }
        or "password" in lower
        or "token" in lower
    )


def write_host_secrets(docker_out: Path, host_out: Path | None = None) -> Path:
    """Mirror Docker-readable fixtures into a host-restricted tree."""
    if docker_out.is_symlink():
        raise RuntimeError(f"refusing to use symbolic-link source directory: {docker_out}")
    if not docker_out.is_dir():
        raise RuntimeError(f"refusing to use non-directory source path: {docker_out}")
    if host_out is None:
        host_out = docker_out.parent / f"{docker_out.name}-host"
    if host_out.is_symlink():
        raise RuntimeError(f"refusing to use symbolic-link output directory: {host_out}")
    if host_out.exists() and not host_out.is_dir():
        raise RuntimeError(f"refusing to use non-directory output path: {host_out}")
    host_out.mkdir(parents=True, exist_ok=True)
    for src in sorted(docker_out.iterdir()):
        if src.is_symlink():
            raise RuntimeError(f"refusing to copy symbolic-link source: {src}")
        if not src.is_file() or src.name in {
            "nats.conf",
            "valkey.conf",
            "valkey.acl",
            "control-valkey.acl",
            "README.txt",
        }:
            continue
        dest = host_out / src.name
        _prepare_write(dest)
        dest.write_bytes(src.read_bytes())
        try:
            dest.chmod(0o600 if _is_private_secret_name(src.name) else 0o644)
        except OSError:
            pass
    readme = host_out / "README.txt"
    _prepare_write(readme)
    readme.write_text(
        "HOST-SIDE live-mTLS fixtures for Rust/Python clients.\n"
        "Private keys and credential files are mode 0600.\n"
        "Docker services must keep using the sibling secrets/ tree (0644 keys).\n"
        "Regenerated by generate_pki.py (write_host_secrets).\n",
        encoding="utf-8",
    )
    return host_out
