//! Real mTLS component evidence for the public browser management bridge.
//!
//! This is not browser-session/OIDC or PostgreSQL persistence acceptance. The
//! peer delegates business operations to the real handler and in-memory
//! idempotency store; only oversized responses and a lost reply are injected.
//!
//! Requires `--features postgres` to expose the browser API. Every test requires
//! APEX_BROWSER_TEST_PKI_DIR; absent/missing fixtures fail, never skip.
//! That directory must contain trusted-host/ and untrusted-host/, independently
//! generated by the existing deploy/compose/live-mtls/generate_pki.py:
//!
//! python -B deploy/compose/live-mtls/generate_pki.py --out <fresh-root>/trusted
//! python -B deploy/compose/live-mtls/generate_pki.py --out <fresh-root>/untrusted
//!
//! The generator also creates sibling *-host directories. Verify that all four
//! destinations are fresh and owned before running it. Set the environment to
//! <fresh-root>, then main runs:
//!
//! cargo test -p apex-control-plane-api --features postgres --test browser_management_tls -- --nocapture
//!
//! No test generates keys, changes environment variables or uses from_channel.
#![cfg(feature = "postgres")]

#[path = "browser_management_tls/behavior.rs"]
mod behavior;
#[path = "browser_management_tls/peer.rs"]
mod peer;
#[path = "browser_management_tls/support.rs"]
mod support;
#[path = "browser_management_tls/tls.rs"]
mod tls;
