# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import control_pb2 as apex_dot_v1_dot_control__pb2


class ControlGatewayStub(object):
    """Out-of-band (OOB) control command gateway. Independently authenticated
    from the EventIngest data path (see event.proto): a distinct operator
    credential space, not the ingest workload bearer token. Every accepted
    command is durably enqueued to the same event outbox used by ingest and
    surfaces as a `control` event (EventType.CONTROL) in the queryable trace.

    Cooperative v1 semantics only (ADR-0005): this issues commands for the
    instrumented runtime to observe and act on. It never forcibly terminates
    or suspends a process.

    Two RPCs, two *different* credential spaces, and they must never be
    confused:

    SubmitCommand  operator -> gateway. Authenticated with an operator
    credential (static table or Keycloak-issued, see
    control-plane-api/src/auth.rs and keycloak.rs).
    PollCommands   agent workload -> gateway. Authenticated with the
    workload-identity model event-ingest already trusts for
    agent connections: mTLS client certificate pinned to a
    bearer credential bound to exactly one agent_id
    (control-plane-api/src/agent_auth.rs).

    An operator credential cannot poll and an agent credential cannot submit.
    That is ADR-0006's independence requirement carried inward: the authority
    to *issue* a stop and the authority to *retrieve* one are different
    authorities held by different principals.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitCommand = channel.unary_unary(
                '/apex.v1.ControlGateway/SubmitCommand',
                request_serializer=apex_dot_v1_dot_control__pb2.ControlCommandRequest.SerializeToString,
                response_deserializer=apex_dot_v1_dot_control__pb2.ControlCommandResponse.FromString,
                )
        self.PollCommands = channel.unary_unary(
                '/apex.v1.ControlGateway/PollCommands',
                request_serializer=apex_dot_v1_dot_control__pb2.PollCommandsRequest.SerializeToString,
                response_deserializer=apex_dot_v1_dot_control__pb2.PollCommandsResponse.FromString,
                )


class ControlGatewayServicer(object):
    """Out-of-band (OOB) control command gateway. Independently authenticated
    from the EventIngest data path (see event.proto): a distinct operator
    credential space, not the ingest workload bearer token. Every accepted
    command is durably enqueued to the same event outbox used by ingest and
    surfaces as a `control` event (EventType.CONTROL) in the queryable trace.

    Cooperative v1 semantics only (ADR-0005): this issues commands for the
    instrumented runtime to observe and act on. It never forcibly terminates
    or suspends a process.

    Two RPCs, two *different* credential spaces, and they must never be
    confused:

    SubmitCommand  operator -> gateway. Authenticated with an operator
    credential (static table or Keycloak-issued, see
    control-plane-api/src/auth.rs and keycloak.rs).
    PollCommands   agent workload -> gateway. Authenticated with the
    workload-identity model event-ingest already trusts for
    agent connections: mTLS client certificate pinned to a
    bearer credential bound to exactly one agent_id
    (control-plane-api/src/agent_auth.rs).

    An operator credential cannot poll and an agent credential cannot submit.
    That is ADR-0006's independence requirement carried inward: the authority
    to *issue* a stop and the authority to *retrieve* one are different
    authorities held by different principals.
    """

    def SubmitCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PollCommands(self, request, context):
        """Retrieves the commands pending for the *calling agent*.

        Unary, deliberately, rather than server-streaming. Three reasons, all
        about the property ADR-0006 exists to protect -- this channel staying
        reachable when the rest of the platform is degraded:

        1. A streaming RPC pins one gateway task, one HTTP/2 stream and one
        idle connection per agent for the lifetime of the run. A unary poll
        costs a bounded amount of work per call and nothing between calls,
        so a fleet of agents cannot exhaust the control channel simply by
        existing.
        2. A poll is trivially rate-limitable per caller. A long-lived stream
        is not: the cost is in holding it open, which no per-request ceiling
        sees.
        3. Idle long-lived streams are exactly what intermediaries (LBs, egress
        proxies, NAT) silently reap, and a control channel whose failure
        mode is "looks connected, delivers nothing" is the failure this
        whole work item exists to close.

        Delivery is at-least-once with idempotent consumers, the same
        non-negotiable the event pipeline already holds: a command returned by a
        poll whose response never reached the agent becomes visible again after
        the gateway's redelivery window, so enactment must be idempotent
        (stopping an already-stopped loop is a no-op, not an error).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitCommand,
                    request_deserializer=apex_dot_v1_dot_control__pb2.ControlCommandRequest.FromString,
                    response_serializer=apex_dot_v1_dot_control__pb2.ControlCommandResponse.SerializeToString,
            ),
            'PollCommands': grpc.unary_unary_rpc_method_handler(
                    servicer.PollCommands,
                    request_deserializer=apex_dot_v1_dot_control__pb2.PollCommandsRequest.FromString,
                    response_serializer=apex_dot_v1_dot_control__pb2.PollCommandsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'apex.v1.ControlGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ControlGateway(object):
    """Out-of-band (OOB) control command gateway. Independently authenticated
    from the EventIngest data path (see event.proto): a distinct operator
    credential space, not the ingest workload bearer token. Every accepted
    command is durably enqueued to the same event outbox used by ingest and
    surfaces as a `control` event (EventType.CONTROL) in the queryable trace.

    Cooperative v1 semantics only (ADR-0005): this issues commands for the
    instrumented runtime to observe and act on. It never forcibly terminates
    or suspends a process.

    Two RPCs, two *different* credential spaces, and they must never be
    confused:

    SubmitCommand  operator -> gateway. Authenticated with an operator
    credential (static table or Keycloak-issued, see
    control-plane-api/src/auth.rs and keycloak.rs).
    PollCommands   agent workload -> gateway. Authenticated with the
    workload-identity model event-ingest already trusts for
    agent connections: mTLS client certificate pinned to a
    bearer credential bound to exactly one agent_id
    (control-plane-api/src/agent_auth.rs).

    An operator credential cannot poll and an agent credential cannot submit.
    That is ADR-0006's independence requirement carried inward: the authority
    to *issue* a stop and the authority to *retrieve* one are different
    authorities held by different principals.
    """

    @staticmethod
    def SubmitCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/apex.v1.ControlGateway/SubmitCommand',
            apex_dot_v1_dot_control__pb2.ControlCommandRequest.SerializeToString,
            apex_dot_v1_dot_control__pb2.ControlCommandResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PollCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/apex.v1.ControlGateway/PollCommands',
            apex_dot_v1_dot_control__pb2.PollCommandsRequest.SerializeToString,
            apex_dot_v1_dot_control__pb2.PollCommandsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
