# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import event_pb2 as apex_dot_v1_dot_event__pb2


class EventIngestStub(object):
    """The authenticated v1 admission endpoint. Transport middleware establishes
    caller identity before the service passes an envelope to the gateway.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ingest = channel.unary_unary(
                '/apex.v1.EventIngest/Ingest',
                request_serializer=apex_dot_v1_dot_event__pb2.EventEnvelope.SerializeToString,
                response_deserializer=apex_dot_v1_dot_event__pb2.IngestResponse.FromString,
                )


class EventIngestServicer(object):
    """The authenticated v1 admission endpoint. Transport middleware establishes
    caller identity before the service passes an envelope to the gateway.
    """

    def Ingest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventIngestServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ingest': grpc.unary_unary_rpc_method_handler(
                    servicer.Ingest,
                    request_deserializer=apex_dot_v1_dot_event__pb2.EventEnvelope.FromString,
                    response_serializer=apex_dot_v1_dot_event__pb2.IngestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'apex.v1.EventIngest', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EventIngest(object):
    """The authenticated v1 admission endpoint. Transport middleware establishes
    caller identity before the service passes an envelope to the gateway.
    """

    @staticmethod
    def Ingest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/apex.v1.EventIngest/Ingest',
            apex_dot_v1_dot_event__pb2.EventEnvelope.SerializeToString,
            apex_dot_v1_dot_event__pb2.IngestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
